- README.md
With a new syntax it looks as the following:
> Follow github block-quote markdown syntax for the README

- examples/validation/plot_gridsearch_for_da.py
- skada/_pipeline.py
- skada/base.py
- skada/tests/test_pipeline.py
> The selector to pass the params to the base estimator

- examples/datasets/plot_dataset_from_moons_distribution.py
- examples/datasets/plot_shifted_dataset.py
- examples/datasets/plot_variable_frequency_dataset.py
Rather simple quality-of-life improvement to make dataset examples interactive in the editors with the proper support.
> Add code cells markup for dataset examples to make them interactive

- skada/_pipeline.py
- skada/tests/test_pipeline.py
> `make_da_pipeline` helper to allow named estimators

- README.md
- skada/datasets/_base.py
- Replace TCLAdapter by CORALAdapter
- Change typo error
> [DOC] Corrections README and string for DomainAware dataset

- skada/datasets/_samples_generator.py
- skada/datasets/tests/test_samples_generator.py
Fixes Issue #9 
- Switch NotImplementedError to ValueError in samples generator code
- Remove duplicate code
> [FIX] Switch NotImplementedError to ValueError + New test cases

- requirements.txt
- requirements_full.txt
Update requirement files to have flexible version of POT
> Remove version for POT

- skada/_subspace.py
- skada/metrics.py
I'm curious why 'flake8-codestyle' is not spotting those in PRs.
> Fix flake8 errors

- skada/tests/test_reweight.py
Super quick to review
Add test cases to make codevoc happy
> [TO_REVIEW] Add test cases for the Reweight class

- .github/workflows/flake8.yaml
Now flake8 should run automatically on PR
> [Fix] Update flake8.yaml to actually run!

- skada/_utils.py
- skada/tests/test_utils.py
Fix formatting issues introduced with a few recent PRs.
>  Fix flake8 for utils and tests

- README.md
- examples/plot_how_to_use_skada.py
- skada/utils.py
+ Adds a simple example file with how to use skada fro beginers
+ Add some code examples in the redame from this example file
> [MRG] Add simple example to documentation and readme

- examples/plot_how_to_use_skada.py
- skada/_pipeline.py
- skada/base.py
- skada/tests/test_pipeline.py
The idea is to 'detect' that we got DA pipeline as a single step in the pipeline and 'unroll' steps by appending them in the current pipeline.
Closes #98
> Support nested DA pipelines

- skada/datasets/_samples_generator.py
> Include docstring for `label` argument of `make_shifted_datasets`

- README.md
Small modifications of the readme, to make it clearer.
> [MRG] Review of the new readme 

- skada/_reweight.py
Hi,
I make small corrections for both methods, as discussed in #112
> Fix DiscriminatorReweightDensity and ReweightDensity

- skada/_utils.py
> [TO_REVIEW] _find_y_type return enum

- skada/base.py
- skada/tests/test_selector.py
> `SelectSource` and `SelectTarget` selectors

- skada/__init__.py
- skada/_pipeline.py
- skada/_utils.py
- skada/base.py
- skada/tests/test_selector.py
The selector that takes a pair of base estimators: one for sources, another one for targets.
> `SelectSourceTarget` selector

- README.md
- skada/_mapping.py
- skada/_reweight.py
- skada/_self_labeling.py
- skada/_subspace.py
- skada/deep/_adversarial.py
- skada/deep/losses.py
- skada/deep/modules.py
- skada/metrics.py
Hello,
Fixes #91 
Remove duplicate references and update docstrings to match unique references of README.md
> Update readme and add unique references in docstring

- skada/_reweight.py
- skada/tests/test_reweight.py
Add the auto/scale mode in KLIEP as done with sklearn SVC
> [TO_REVIEW] Add the auto/scale mode in KLIEP

- skada/utils.py
When calling the `type_of_target` function we get a ENUM object, while at some places it was expecting a string.
> [TO_REVIEW] Small bug fix check_X_y_domain() + source_target_merge()

- examples/methods/plot_reweighting.py
- skada/_reweight.py
- skada/tests/test_reweight.py
- skada/tests/test_utils.py
- skada/utils.py
Hi everyone,
Here is a new pull request for the frank-wolfe solver for KMM.
I made two qp_solve functions this time: `_qp_solve_scipy` and `_qp_solve_frank_wolfe`
> Add frank-wolfe solver (v2)

- skada/_self_labeling.py
- skada/tests/test_self_labeling.py
- Add kwargs to DASVM predict/predict_proba
- add score func (SupervisedScorer need it)
> [MRG] Add kwargs to DASVM predict/predict_proba + add score func

- skada/deep/tests/test_deep_scorer.py
- skada/metrics.py
> [MRG] Fix issue of the circular validation with deep models

- README.md
- docs/source/all.rst
- examples/methods/plot_subspace.py
- examples/plot_method_comparison.py
- skada/__init__.py
- skada/_subspace.py
- skada/tests/test_subspace.py
- skada/utils.py
Add [TransferSubspaceLearning](https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=4118b4fc7d61068b9b448fd499876d139baeec81) method
> [MRG] Add TransferSubspaceLearning method

- skada/_reweight.py
- skada/tests/test_reweight.py
Fixes #198 
Linked to https://github.com/scikit-adaptation/skada-bench/pull/49
> [TO_REVIEW] Add n_neighbours as an arg of NN RW

- skada/metrics.py
- skada/tests/test_scorer.py
Before when using the Circular validation while using the solver NO_DA_TARGET_ONLY:
```
Traceback (most recent call last):
File "/Users/yanislalou/Documents/CMAP/skada_test_venv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 141, in __call__
score = scorer(estimator, *args, **routed_params.get(name).score)
File "/Users/yanislalou/Documents/CMAP/skada_test_venv/lib/python3.9/site-packages/skada/metrics.py", line 43, in __call__
return self._score(estimator, X, y, sample_domain=sample_domain, **params)
File "/Users/yanislalou/Documents/CMAP/skada_test_venv/lib/python3.9/site-packages/skada/metrics.py", line 586, in _score
backward_estimator.fit(X, backward_y, sample_domain=backward_sample_domain)
File "/Users/yanislalou/Documents/CMAP/skada_test_venv/lib/python3.9/site-package …
```
> [TO_REVIEW] Fix Circular validation for NO_DA_TARGET_ONLY

- skada/datasets/_amazon_review.py
- skada/datasets/_office_home.py
Following discussion with @YanisLalou:
- Add reference for Office-Home dataset
- Remove wrong reference and add the correct one for Amazon Review Dataset
> [TO REVIEW] Clean datasets references

- skada/_utils.py
- skada/base.py
- skada/metrics.py
- skada/model_selection.py
> [MRG] Incorporate sklearn 1.5.0 changes that are incompatible

- skada/datasets/_samples_generator.py
Hi everyone,
This little change enables to modify the covariate shift center
> Add a cov_shift_center parameter to move the center of the covariate shift

- skada/metrics.py
- skada/model_selection.py
- skada/tests/test_cv.py
- skada/tests/test_scorer.py
- skada/tests/test_utils.py
- In cv functions the `allow_nd` was wrongfully set to `False`
- Add tests for `check_X_domain` and `check_X_y_domain`
- Add tests for cv
> [WIP] Allow model selection cv to handle nd inputs

- skada/tests/test_reweight.py
> [MRG] Uncomment MMDTarSReweightAdapter tests

- skada/deep/_adversarial.py
- skada/deep/base.py
> Batchnormfix2

- skada/deep/utils.py
There a bug when `n_samples == n_centroids`: the dissimilarity is a matrix of size `(n_samples, n_samples)` instead of being a vector `(n_samples, )`.
This PR solves this issue by creating two different functions `_compute_dissimilarity_loss` and `_compute_dissimilarity_matrix`.
> [MRG] Fix dissimilarities computations of Deep CAN
