skada/_pipeline.py
skada/tests/test_pipeline.py

Closes #13.
Provides rather rigid handling for what might and might not be a default selectors. Tests are implemented for all edge cases.

Pipeline to respect `default_selector` parameters

---

README.md
examples/methods/plot_optimal_transport_da.py
examples/validation/plot_cross_val_score_for_da.py
examples/validation/plot_gridsearch_for_da.py
skada/datasets/_base.py
skada/datasets/tests/test_base.py
skada/tests/test_cv.py
skada/tests/test_mapping.py
skada/tests/test_pipeline.py
skada/tests/test_reweight.py
skada/tests/test_scorer.py
skada/tests/test_subspace.py

Change the name of the method to be precise that the out is only useful when doing Leave-One-Domain-Out.
Additional docstrings are provided as well.
Closes #5.

Rename `pack_flatten` to `pack_for_lodo`

---

README.md
skada/datasets/_base.py
skada/datasets/_office.py
skada/datasets/_samples_generator.py

#25 
- Rename Bunch keys in the `DomainAwareDataset` def

Rename Bunch keys

---

README.md

The OTMappingAdapter class doesnt accept 'reg' as an argument.

[DOC] Small README fix

---

skada/datasets/_base.py
skada/datasets/tests/test_base.py

Issue #12 
- Handling the str output of a DomainAwareDataset if the number of domin_names_ is too large
- Print the number of datapoints in the dataset

DomainAwareDataset str repr edge case handling

---

.circleci/config.yml
.github/workflows/testing.yml
requirements.txt

Right now building of docs fails because old dev0 version is missing.

Switch from dev0 to stable sklearn 1.4.0

---

skada/base.py
skada/tests/test_selector.py

Closes #83.
```python
import numpy as np
from sklearn.linear_model import LinearRegression
from skada import KLIEP
X_source = np.ones(10)
X_target = X_source
y_source = np.ones(10)
y_target = np.zeros(10)
from skada.datasets import DomainAwareDataset
dataset = DomainAwareDataset([(X_source, y_source, 's'), (X_target, y_target, 't')])
X, y, sample_domain = dataset.pack_train(as_sources=['s'], as_targets=['t'])
lr = LinearRegression()
kliep = KLIEP(base_estimator=lr)
kliep.fit(X.reshape(-1, 1), y, sample_domain=sample_domain)
kliep.predict(X.reshape(-1, 1))
Out[7]:
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
1., 1., 1.])
```

Fix masked inputs filtering in the base selector for regression tasks

---

examples/plot_method_comparison.py
skada/_reweight.py
skada/base.py
skada/tests/test_reweight.py
skada/tests/test_scorer.py
skada/tests/test_selector.py

Covers both #89 and #7 
Now, when we create a pipeline with the adapter that outputs `sample_weight` but the next estimator in the pipeline does not accept it, the following exception is thrown
```
E    skada.base.IncompatibleMetadataError: The adapter provided 'sample_weight' parameter which is not explicitly set as requested or not for 'LogisticRegression.fit'.
E    Make sure that metadata routing is properly setup, e.g. by calling 'set_fit_request()'. See documentation at https://scikit-learn.org/stable/metadata_routing.html
```
`IncompatibleMetadataError` overrides sklearn exception `UnsetMetadataPassedError`, when it's clear that the latter was caused by the incompatibility between adapter output and the parametrization of the estimator. All test cases are updated accordingly.

Properly process `sample_weight` when using reweight adapters

---

examples/plot_method_comparison.py

Hi everyone,
I open this PR to fix a little bug in the `plot_method_comparison.py` example. Target labels were given to the fit methods, they are now removed (cf. #83).
The reweighting method are still not working, but it should be resolved soon, with PR #90

Remove target labels in the method comparison example

---

skada/base.py
skada/tests/test_selector.py

This is mostly technical detail to stay consistent with how sklearn's metadata routing is designed: `BaseSelector` object is a meta-estimator thus the routing should return `MetadataRouter` object with mapping between methods.
Closes #14

Convert `BaseSelector` to the metadata router

---

skada/_reweight.py
skada/base.py
skada/tests/test_selector.py
skada/tests/test_subspace.py

* cleanup code for adaptation output processing by moving `X` to an attribute instead of keys
* fix documentation for reweight adapters ('returns' section of docstrings)

Update `AdaptationOutput` to make `X` into an attribute

---

conftest.py
skada/tests/test_mapping.py

Just to make sure that calling convention is consistent across all use cases.

Update previously used dataset fixture

---

skada/_utils.py
skada/base.py
skada/tests/test_pipeline.py
skada/tests/test_selector.py

Per the discussion in Slack.
`Selector` now removes masked inputs if the base estimator does not accept `sample_domain` through the routing (e.g. any sklearn estimator out there). The contract is that if the estimator declares `sample_domain` as a parameter, it should be able to deal with inputs being partially masked (presumably targets).

Remove masked inputs only if estimator does not accept `sample_domain`

---

README.md
docs/source/all.rst
skada/metrics.py
skada/tests/test_scorer.py

Fixes #111 
Paper: https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=4803844&tag=1
Process described in part [5] and [6].
Small thing not in the paper but implemented:
- If the estimator predicts always the same value, then we assume that the `backward_estimator` will also predicts  always the same value.
--> Why? Because for some estimators, if you train them with np.unique(y) = 1 you get ValueErrors (happens with SVC).

[MRG] Implement CircularValidation as a scorer

---

skada/_pipeline.py
skada/base.py

With #123 being merged the selector does not check if estimator was 'final' in the pipeline. Thus the API for marking is not needed.

No need for mark-as-final operation

---

skada/_utils.py
skada/base.py
skada/tests/test_selector.py

This is an addition to the functionality implemented in #123.
The question here is the following:
```python
pipe = make_da_pipeline(StandardScaler(), SubspaceAlignmentAdapter(), LogisticRegression())
pipe.fit(X=X_train, y=y_train, sample_domain=sample_domain)
```
Assuming `y_train` is properly masked. Now
* `SubspaceAlignmentAdapter` gets everything because it declares `sample_domain` in the routing.
* `LogisticRegression` gets only sources (can't work with `sample_domain`)
* `StandardScaler` ??? 
This PR makes it so `StandardScaler` gets both sources **and** targets, as `fit` does not require labels. It previously worked this way, and it seems like this is a much stronger default. For non default behavior, we still can wrap the transformer into a proper selector when those are ready (see …

Selector to avoid filtering out masked samples when fitting transformer

---

conftest.py
skada/_reweight.py
skada/tests/test_reweight.py

This PR fixes the `numpy` random seed in every tests.
It also fixes the TarS method when only a subset of classes are present in the target domain.

[MRG] Fix tests random seed and TarS

---

skada/_ot.py
skada/tests/test_ot.py

Fixes #150 
Some scorers need the estimator to have a `predict_proba` function.
Now its the case with jdot

[MRG] Add predict_proba for jdot

---

skada/metrics.py

With the `CircularValidation` scorer we fit an estimator on the prediction of X_source i.e y_pred_source.
However some estimator only supports labels in [0, num_classes-1], which is not guaranteed.
Indeed for some iterations, `ValueError` were raised:
`ValueError: Invalid classes inferred from unique values of 'y'.  Expected: [0 1 2 3 4 5 6], got [1 2 3 4 7 8 9]
`
**Solution:**
Re-encode the labels before feeding them to the estimator.

[MRG] CircularValidation: Re-encode y labels before training the estimator on y_source_pred

---

skada/_self_labeling.py
skada/tests/test_self_labeling.py

A lot of skada scorers need the estimator to have the `predict_proba` method.
So here we implement it depending on if the `base_estimator` has it or not.

[MRG] Add predict_proba to DA_SVM

---

skada/base.py
skada/tests/test_pipeline.py
skada/tests/test_self_labeling.py
skada/utils.py

Code sample from the Slack conversation:
```python
from pyriemann.estimation import Covariances
from pyriemann.tangentspace import TangentSpace
from skada import make_da_pipeline
from skada import CORALAdapter
import numpy as np
from skada.datasets import DomainAwareDataset
pipe = make_da_pipeline(
Covariances(estimator='oas'),
TangentSpace(),
CORALAdapter()
)
Xs = np.random.randn(100, 22, 30)
Xt = np.random.randn(100, 22, 30)
ys = np.random.randint(0, 2, 100)
yt = np.random.randint(0, 2, 100)
dataset = DomainAwareDataset()
dataset.add_domain(Xs, ys, 'source')
dataset.add_domain(Xt, yt, 'target')
X, y, sample_domain = dataset.pack_train(as_sources=["source"], as_targets=["target"])
pipe.fit(X, y, sample_domain=sample_domain)
```

Allow multi dim inputs through the pipeline

---

skada/deep/_adversarial.py
skada/deep/base.py
skada/deep/tests/test_deep_adversarial.py

The input size of domain_classifier is n_classes * n_features, so I propose to add n_classes as argument of CDAN to create domain_classifier with the right input size when it's not provided.

Fix CDAN input to domain_classifier and gpu compatibility

---

skada/_mapping.py
skada/tests/test_mapping.py

Before when using the DeepValidation scorer we had this error:
```Traceback (most recent call last):
File "/Users/yanislalou/Documents/CMAP/skada_test_venv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 141, in __call__
score = scorer(estimator, *args, **routed_params.get(name).score)
File "/Users/yanislalou/Documents/CMAP/skada_test_venv/lib/python3.9/site-packages/skada/metrics.py", line 43, in __call__
return self._score(estimator, X, y, sample_domain=sample_domain, **params)
File "/Users/yanislalou/Documents/CMAP/skada_test_venv/lib/python3.9/site-packages/skada/metrics.py", line 433, in _score
y_pred = estimator.predict_proba(
File "/Users/yanislalou/Documents/CMAP/skada_test_venv/lib/python3.9/site-packages/sklearn/pipeline.py", line 728, in predict_proba
Xt = …
```

[MRG] MMDLS handle case where we have X_source and no y_source

---

skada/_subspace.py
skada/tests/test_subspace.py

This PR:
- fixes SA by removing the multiplication by `M` on the target data
- changes `n_components` from 2 to 1 in tests because data are only 2d
- changes the function name `test_subspace_alignment` for `test_subspace_estimator` because it tests all subspace methods

[TO_REVIEW] Fix subspace alignment

---

setup.cfg

On a fresh system, running `pytest --collect-only` will run the examples. This is typically done by the pytest extension of VSCode, which is annoying.
This fixes the test collection.

FIX test collection don't run examples

---

skada/_mapping.py
skada/_utils.py
skada/tests/test_mapping.py

In https://arxiv.org/abs/1612.01939, the authors assume source and target data have a zero mean, i.e. $\mu_S=\mu_T=0$.
This PR adds an `assume_centered` argument to CORAL to center data during fitting and transforming data.

[WIP] Center data when using transform of coral

---

skada/deep/_adversarial.py
skada/deep/_divergence.py
skada/deep/_optimal_transport.py
skada/deep/base.py

[MRG] Add a parameter base_criterion to deep models

---

README.md
docs/source/all.rst
skada/deep/tests/test_deep_scorer.py
skada/metrics.py
skada/tests/test_scorer.py

Implementation of the paper:
https://proceedings.neurips.cc/paper_files/paper/2023/file/7721f1fea280e9ffae528dc78c732576-Paper-Conference.pdf

[MERGE] Add new scorer: MixValScorer

---

docs/source/all.rst
skada/_utils.py
skada/tests/test_utils.py
skada/utils.py

**Updated Documentation:**
- `skada.source_target_split`
- `skada.per_domain_split`
- `skada.utils.check_X_y_domain`
- `skada.utils.extract_source_indices`
- `skada.utils.extract_domains_indices`
- `skada.utils.source_target_merge`
**Issue Resolved:**
The example for `skada.utils.source_target_merge` failed when `y_target=None` because the function was generating `y_target` with `_DEFAULT_MASKED_TARGET_REGRESSION_LABEL`, even for classification tasks. This caused a type mismatch when merging arrays (`int` vs. `nan`). `nan` were then casted as `int` with specific value `-9xxxxx`.

[TO_REVIEW] Add utilities functions to the doc

---

skada/deep/_baseline.py
skada/deep/tests/test_deep_scorer.py
skada/metrics.py

The `SourceOnly` and `TargetOnly` methods were not functioning as expected.
The default behavior was overriding the layer names, setting them to `None`, which caused the issue.
- Removed the default `None` assignment for layer names in the `selectSource` and `selectTarget` methods.
- Add relevant test cases to ensure proper functionality.

Fix: Dev scorer wasn't working with SourceOnly and TargetOnly

---

conftest.py
skada/tests/test_label_prop.py
skada/tests/test_mapping.py
skada/tests/test_ot.py
skada/tests/test_pipeline.py
skada/tests/test_reweight.py
skada/tests/test_scorer.py
skada/tests/test_selector.py

Right now, in `conftest.py`, some fixtures return a tuple (X, y, sample_domain) while some others return a DomainAwareDataset.
This PR aims to unify `conftest.py` so that every fixture returns a DomainAwareDataset. Developing tests should be easier with this PR.

[WIP] Harmonize fixtures

---

skada/_pipeline.py
skada/tests/test_pipeline.py

**Enhancement: Add compatibility with `None` in `skada` pipelines**
This PR introduces support for using `None` within `skada` pipelines, similar to how `scikit-learn` handles it. For example:
```Python
pipe = make_pipeline(
StandardScaler(),
None,  # Skip step
PCA(),
LogisticRegression(),
)
```
Now, `skada` pipelines can also include `None` as a step:
```Python
pipe = make_da_pipeline(
StandardScaler(),
None,  # Skip step
PCA(),
SubspaceAlignmentAdapter(n_components=2),
LogisticRegression(),
)
```

[TO_REVIEW] Bug fix when None in make_da_pipeline

---

skada/metrics.py
skada/tests/test_scorer.py

This pull request includes changes to handle cases where there are no indices for intra-cluster or inter-cluster evaluations in the `MixValScorer`, and updates the corresponding tests to ensure these cases are properly handled.
* [`skada/metrics.py`](diffhunk://#diff-4384c62462d0266c1d4ec08aac2e33b735a06e87000ff0ab0f11a8523862cd3bR776-R778): Added checks to set `ice_same` and `ice_diff` to `np.nan` if their respective index lists are empty. Modified the calculation of `ice_score` to use `np.nanmean` instead of a simple average. [[1]](diffhunk://#diff-4384c62462d0266c1d4ec08aac2e33b735a06e87000ff0ab0f11a8523862cd3bR776-R778) [[2]](diffhunk://#diff-4384c62462d0266c1d4ec08aac2e33b735a06e87000ff0ab0f11a8523862cd3bR787-R789) [[3]](diffhunk://#diff-4384c62462d0266c1d4ec08aac2e33b735a06e87000ff0a …

[TO_REVIEW] Handle edge case Mixvalscorer

---

README.md
docs/source/all.rst
skada/deep/__init__.py
skada/deep/_divergence.py
skada/deep/callbacks.py
skada/deep/losses.py
skada/deep/tests/test_deep_divergence.py
skada/deep/utils.py

Paper: https://arxiv.org/pdf/1901.00976
Mostly eq 3-4-5 + paragraph 3.4
* **CAN and CANLoss Implementation:**
* Added `CANLoss` class to `skada/deep/_divergence.py` to implement the contrastive domain discrepancy (CDD) loss. 
* Added `CAN` function to `skada/deep/_divergence.py` to implement the CAN domain adaptation method. 
* **SphericalKMeans:**
* Added `SphericalKMeans` class to `skada/deep/utils.py` for clustering using cosine similarity.
* **New Tests for CAN:**
* Added tests for CAN in `test_deep_divergence.py` to ensure the new method works as expected.
* Double check the implementation

[WIP] Add CAN Method

---

skada/deep/base.py
skada/deep/tests/test_deep_base.py
skada/deep/tests/test_deep_baseline.py
skada/deep/tests/test_deep_scorer.py
skada/metrics.py

The most important changes include adding support for source domains in various methods and updating the scoring mechanism to accommodate these changes.
Enhancements to `DomainAwareNet`:
* Added `allow_source` parameter to `predict`, `predict_proba`, and `score` methods to support source domains. (`skada/deep/base.py`) [[1]](diffhunk://#diff-7f8e921886d16f3ba7b7d824a3ed03e64e0fa03c2f972325004a6a518cfff23eR575) [[2]](diffhunk://#diff-7f8e921886d16f3ba7b7d824a3ed03e64e0fa03c2f972325004a6a518cfff23eR620-R621) [[3]](diffhunk://#diff-7f8e921886d16f3ba7b7d824a3ed03e64e0fa03c2f972325004a6a518cfff23eR668)
* Modified `check_X_domain` usage in `predict_proba` and `score` methods to handle `allow_source`. (`skada/deep/base.py`) [[1]](diffhunk://#diff-7f8e921886d16f3ba7b7d824a3ed03e64e0fa03c2f97232500 …

[TO_REVIEW] Enhancements to DomainAwareNet and Scorers to handle `allow_source` arg

---

skada/deep/base.py
skada/deep/tests/test_deep_base.py
skada/deep/utils.py

The `predict_proba` of deep method was choosing the nonlin attributes by looking at `criterion` attribute of the solvers. The `DomainAwareNet` has a `DomainAwareCriterion` as criterion. We should choose the nonlin base on `criterion.base_criterion`. This PR does that.

[MRG] fix `predict_proba` for deep method

---

skada/__init__.py
skada/tests/test_transformers.py
skada/transformers.py

- Fix `TypeError: DomainStratifiedSubsampleTransformer.transform() got an unexpected keyword argument 'allow_source'`with `DomainStratifiedSubsampleTransformer` 
- Add `DomainAndLabelStratifiedSubsampleTransformer` to have a transformer preserving the percentage of samples
for each class and for each sample domain (To prevent issues like: `ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: 1`)

[MRG] Add `DomainAndLabelStratifiedSubsampleTransformer` + Fix `DomainStratifiedSubsampleTransformer`

---

skada/tests/test_utils.py
skada/utils.py

In response to #16 
@kachayev is that what you had in mind ?
Should `check_X_y_domain` and `check_X_domain` stay two separate functions?
A test should be added for this situation.

[MRG] Check if sample_domain have only unique domains indexes in check_*_domain

---

skada/deep/_class_confusion.py
skada/deep/losses.py
skada/deep/tests/test_deep_class_confusion.py

This pull request includes changes to the `mcc_loss` function to handle zero probabilities correctly, updates to the corresponding tests, and necessary imports.
* [`skada/deep/losses.py`](diffhunk://#diff-0774706cdd6571bdf61f65dbc2fe0fd5c9e6ae928b28459a523339e962180212L398-R399): Added a small epsilon value to avoid taking the logarithm of zero, which can lead to numerical issues. (`[skada/deep/losses.pyL398-R399](diffhunk://#diff-0774706cdd6571bdf61f65dbc2fe0fd5c9e6ae928b28459a523339e962180212L398-R399)`)
* [`skada/deep/tests/test_deep_class_confusion.py`](diffhunk://#diff-71736bf2bcae56dd6073bdfd1c728374aa1b4f9d9a72594e27a02b269b14a169R59-R81): Added a new test `test_mcc_with_zeros` to ensure that the `mcc_loss` function handles zero probabilities correctly. …

[TO_REVIEW] Add epsilon in MCC to prevent log(0)

---

skada/deep/_divergence.py
skada/deep/losses.py
skada/deep/tests/test_deep_divergence.py

This pull request includes a change to improve the robustness of the `dan_loss` function. The change include adding a small epsilon to avoid division by zero, and adding a new test case for an edge case.
* [`skada/deep/losses.py`](diffhunk://#diff-0774706cdd6571bdf61f65dbc2fe0fd5c9e6ae928b28459a523339e962180212L178-R181): Added a small epsilon to the median pairwise distance calculation to avoid potential division by zero issues. (`[skada/deep/losses.pyL178-R181](diffhunk://#diff-0774706cdd6571bdf61f65dbc2fe0fd5c9e6ae928b28459a523339e962180212L178-R181)`)
* [`skada/deep/tests/test_deep_divergence.py`](diffhunk://#diff-4a4c6ab899ff86f7bc4d7db095dfc066f1a8b843ac58284dbc9cb8d565b5584bR200-R216): Added a new test case `test_dan_loss_edge_cases` to verify the behavior of `dan_loss` with edge …

[MRG] Handle edge case for DAN

---

README.md
docs/source/all.rst
skada/deep/__init__.py
skada/deep/_adversarial.py
skada/deep/modules.py
skada/deep/tests/test_deep_adversarial.py

Implement the MDD method from https://arxiv.org/pdf/1904.05801. 
Related issue: #254
*Core implementation*
*Documentation*

[MRG] Add MDD method

---

skada/deep/_divergence.py
skada/deep/callbacks.py
skada/deep/losses.py
skada/deep/tests/test_deep_divergence.py
skada/deep/utils.py

This pull request includes changes to improve the spherical k-means clustering implementation.
Refactoring of clustering process:
* When using pre-initialised centroids, we do not run the k-means algorithm multiple times. Indeed in that case, the centroids will always have the same position.
Addition of helper method:
* Introduced `_run_single_kmean` method to encapsulate the logic for running a single spherical k-means clustering iteration, which includes computing dissimilarities, updating centroids, and checking for convergence. [[1]](diffhunk://#diff-7424c2462888e7d03099300b412067b00f00c28655a03e22dbc5b94b3d32686fL201-R241) [[2]](diffhunk://#diff-7424c2462888e7d03099300b412067b00f00c28655a03e22dbc5b94b3d32686fL227-R263)

[TO_REVIEW] Remove redundant centroid computation in spherical k-means

---

skada/deep/__init__.py
skada/deep/_adversarial.py
skada/deep/tests/test_deep_adversarial.py

Use equations (26)-(29) from https://arxiv.org/pdf/1904.05801

[MRG] Fix mdd loss

---

skada/tests/test_utils.py
skada/utils.py

When doing `source_target_merge(X_source, X_target)`, if one of the two `X_source` (or `X_target`) is empty then it infers what should be its default value based on the other one using the `_find_y_type` function.
This PR avoids this by checking the length of `sample_domain` for the empty `X_source` or `X_target`. If the length is 0, then it skips the imputation.

[MRG] do not try to complete when X_source is empty

---

README.md
docs/source/all.rst
skada/deep/tests/test_deep_scorer.py
skada/metrics.py
skada/tests/test_scorer.py

Implementation of [MaNo](https://arxiv.org/pdf/2405.18979) as an unsupervised realistic scorer.
This should answer #288.

[WIP] Add new scorer: MaNoScorer

---

CONTRIBUTING.md

Update the dependency installation in CONTRIBUTING.md to solve the import problem for users using .venv virtual env and not conda virtual envs.
*Update*: the problem was coming from using zsh or bash terminal and not on the kind of virtual env used

[TO REVIEW] Update CONTRIBUTING.md
